server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/one_car_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB

# mybatis 配置
mybatis:
  mapper-locations: mappers/*.xml # 配置mapper路径
  config-location: classpath:mybatis-config.xml # 配置配置文件路径






